#!/bin/bash
# Quick Reference - Common Commands

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           Resculance API - Quick Reference                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 DATABASE SETUP"
echo "  make db-setup-ci          → Complete setup (reset + migrate + seed)"
echo "  npm run db:setup:ci       → Same as above (npm version)"
echo "  npm run db:reset          → Reset database only"
echo "  npm run db:migrate        → Run migrations only"
echo "  npm run db:seed           → Seed data only"
echo ""
echo "🚀 SERVER"
echo "  npm run dev               → Start in development mode"
echo "  npm start                 → Start in production mode"
echo "  node src/server.js &      → Start in background"
echo "  pkill -f 'node.*server'   → Stop server"
echo "  lsof -i :5000             → Check if port 5000 is in use"
echo ""
echo "🧪 TESTING"
echo "  ./test-rbac.sh            → Run RBAC tests (12 tests)"
echo "  ./verify-data.sh          → Verify data visibility"
echo "  ./test-apis.sh            → Test all API endpoints"
echo ""
echo "🔐 TEST ACCOUNTS"
echo "  Superadmin:    superadmin@resculance.com / Super@123"
echo "  AIIMS Admin:   admin@aiims.delhi / Admin@123"
echo "  FastAid Admin: admin@fastaid.com / Admin@123"
echo ""
echo "📡 API ENDPOINTS"
echo "  Base URL: http://localhost:5000/api/v1"
echo ""
echo "  Auth:"
echo "    POST   /auth/login              → Login (returns accessToken)"
echo "    POST   /auth/register           → Register new user"
echo "    POST   /auth/refresh-token      → Refresh access token"
echo ""
echo "  Users (RBAC):"
echo "    GET    /users                   → List users (filtered by role)"
echo "    GET    /users/:id               → Get user details"
echo "    POST   /users                   → Create user"
echo "    PUT    /users/:id               → Update user"
echo ""
echo "  Ambulances (RBAC):"
echo "    GET    /ambulances              → List ambulances (filtered by role)"
echo "    GET    /ambulances/:id          → Get ambulance details"
echo "    POST   /ambulances              → Create ambulance"
echo ""
echo "  Patient Sessions (RBAC):"
echo "    GET    /patients/sessions       → List trips (filtered by role)"
echo "    GET    /patients/sessions/:id   → Get trip details"
echo "    POST   /patients/onboard        → Create new trip"
echo ""
echo "  Collaborations (RBAC):"
echo "    GET    /collaborations          → List partnerships (filtered)"
echo "    POST   /collaborations          → Create partnership request"
echo "    PUT    /collaborations/:id      → Update partnership status"
echo ""
echo "  Organizations:"
echo "    GET    /organizations           → List all organizations"
echo "    GET    /organizations/:id       → Get organization details"
echo ""
echo "  Dashboard:"
echo "    GET    /dashboard/stats         → Get dashboard statistics"
echo ""
echo "📊 DATABASE INFO"
echo "  Host:     localhost"
echo "  Port:     3306"
echo "  Database: resculance_db"
echo "  User:     resculance_user"
echo ""
echo "  Tables:"
echo "    • users                    (15 records)"
echo "    • organizations            (7 records)"
echo "    • ambulances              (5 records)"
echo "    • patient_sessions        (3 records)"
echo "    • collaboration_requests  (3 records)"
echo "    • patients"
echo "    • ambulance_devices"
echo "    • vital_signs"
echo "    • communications"
echo "    • audit_logs"
echo ""
echo "✅ RBAC RULES"
echo "  Superadmin:       Sees ALL data across all organizations"
echo "  Hospital Admin:   Sees only their hospital's trips & partnerships"
echo "  Fleet Admin:      Sees only their fleet's ambulances & partnerships"
echo "  Staff:            Filtered by their organization"
echo ""
echo "🔧 TROUBLESHOOTING"
echo "  Server won't start?"
echo "    → Check if port 5000 is in use: lsof -i :5000"
echo "    → Check logs: tail -f server.log"
echo ""
echo "  Database errors?"
echo "    → Reset and setup: make db-setup-ci"
echo "    → Check connection in src/config/database.js"
echo ""
echo "  RBAC not working?"
echo "    → Run tests: ./test-rbac.sh"
echo "    → Check JWT token in browser DevTools"
echo ""
echo "📝 FILES TO CHECK"
echo "  Configuration:"
echo "    • src/config/database.js         → DB connection"
echo "    • src/config/constants.js        → App constants"
echo "    • .env                           → Environment variables"
echo ""
echo "  Models (Schema-aligned):"
echo "    • src/models/PatientSession.js   → ✅ Fixed (6 methods)"
echo "    • src/models/CollaborationRequest.js → ✅ Fixed (5 methods)"
echo "    • src/models/User.js"
echo "    • src/models/Ambulance.js"
echo ""
echo "  Controllers (RBAC-enabled):"
echo "    • src/controllers/patientController.js       → ✅ Fixed"
echo "    • src/controllers/collaborationController.js → ✅ Fixed"
echo "    • src/controllers/userController.js"
echo "    • src/controllers/ambulanceController.js"
echo ""
echo "  Tests:"
echo "    • test-rbac.sh              → RBAC verification (12 tests)"
echo "    • verify-data.sh            → Data visibility check"
echo ""
echo "📚 DOCUMENTATION"
echo "  • PROJECT_STATUS.md                    → Current status"
echo "  • RBAC_IMPLEMENTATION_COMPLETE.md      → RBAC details"
echo "  • README.md                            → Setup guide"
echo "  • api_document.txt                     → API documentation"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Status: ✅ ALL SYSTEMS OPERATIONAL - Production Ready         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
